version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    # ports:
    #  - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    # ports:
    #   - "3001:3002"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tworkman
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db: