version: "3"
services:
  node-app:
    build: .
    ports:
      - "3001:3002"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=3002
    env_file:
      - ./.env